# Uncomment the next line to define a global platform for your project
# platform :ios, '15.2'

target 'PPangDelivery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'SnapKit'
	pod 'NMapsMap'

  # Pods for PPangDelivery

end
