# Uncomment the next line to define a global platform for your project
# platform :ios, '15.2'

target 'PPangDelivery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'SnapKit', '~> 5.6.0'
	pod 'NMapsMap', '~> 3.15.0'
	pod 'Then'

	pod 'FirebaseAnalytics'
	pod 'FirebaseAuth'
	pod 'FirebaseFirestore'
	
	pod 'Then'

  # Pods for PPangDelivery
end
